application: ayr-www
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /img
  static_dir: assets/img

- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  
- url: .*
  script: main.app
